### PR TITLE
Bugfix/update syntastic doc

### PR DESCRIPTION
**Pull request by austincrft**
Updated the doc to say that syntastic support must be enabled.

### CODE REVIEW

**Comment by austincrft** [comment]
In response to #58. I don't believe this completely solves the problem, but indicates that it must be enabled.

I tried using the method stated in [Syntastic's External Checker info](https://github.com/scrooloose/syntastic/wiki/Syntax-Checker-Guide#7-external-checkers), but it still wouldn't load automatically.

**Comment by kjnilsson** [comment]
So this PR makes it better but doesn't completely solve #58 ? What is missing?

**Comment by austincrft** [comment]
Well, that depends on what the goal is. I think the best-case scenario would be that the user doesn't have to configure the checkers manually in their `.vimrc`.

I'm not totally sure that's possible. I couldn't get it working following the steps in Syntastic's guide.

**Comment by kjnilsson** [comment]
Hi - why did you close this?

**Comment by austincrft** [comment]
Oh, my bad. I deleted the branch on my fork without realizing I still had an open PR. I'll restore it when I get back to my computer.

**Comment by kjnilsson** [comment]
Ok cool - I've been doing some work on the other PR this weekend. Would like to include the project.json support for now so have pulled your changes and made a few amendments. Should hopefully be ready to push fairly soon.

**Comment by austincrft** [comment]
There we go. Reopened.

**Comment by kjnilsson** [comment]
Cheers.

**Pull request merged**
