### PR TITLE
Match build.fsx to Makefile #7

### PR DESCRIPTION
**Pull request by panesofglass**

### CODE REVIEW

**Comment by forki** [comment]
If you keep using nuget then you should keep the restorepackages phase in the build script

**Comment by panesofglass** [comment]
NuGet is only needed to fetch FAKE from install.cmd.

**Comment by forki** [comment]
Then it should be easy to switch to paket bootstrapper ;-)

**Comment by rneatherway** [comment]
I would definitely switch to Paket. The nuget usage and path `../lib/nuget/nuget.exe` is from when this was a subdirectory in the fsharpbinding repository. I think there is no need to stick with nuget now.

**Comment by panesofglass** [comment]
I'll add that later today!

**Comment by panesofglass** [comment]
I actually thought about switching to powershell, as that would not require us to download any other tools. Thoughts?

**Comment by panesofglass** [comment]
Hmm, though I suppose FAKE + Paket would be sufficient for a single "build" script.

**Comment by rneatherway** [comment]
If you are thinking of removing the Makefile and just using Paket/FAKE then there could just be a single build script, which is better than having two probably. As I said on #7 the benefit of using Make is that it handles dependencies better than FAKE (which doesn't avoid recompilation or patterns like .el -> .elc unless I'm mistaken), but if that isn't needed and the Makefile is just a glorified shell script then it seems reasonable to use FAKE.

**Comment by rneatherway** [comment]
(But @kjnilsson would know best for this repo)

**Comment by panesofglass** [comment]
I won't remove the Makefile; I will just add a build.sh.

**Comment by panesofglass** [comment]
Honestly, bash and powershell are probably sufficient.

**Comment by panesofglass** [comment]
FWIW, I'm happy to remove the PowerShell attempt. I thought that might be simple, but I'm no PowerShell expert. Perhaps @ctaggart or some other PS whiz could help if there's interest.

**Comment by panesofglass** [comment]
Please note, while I added `install.sh`, I have not tested it on *nix. I tried it in Git Bash, and it fails b/c of `WebClient.DownloadFile`, so it may not work on *nix.

**Comment by rojepp** [comment]
In sublime, I let paket handle the downloading of FSAC, I thought it was neat. :) 
https://github.com/fsharp/sublime-fsharp-package/pull/5 
Still have to unzip it though.

**Pull request merged**
